---

- name: "Create docker secret '{{ docker_secret.name }}' for '{{ docker_compose_service_name }}'"
  no_log: true
  become: true
  # TODO(Montellese) use "docker secret"
  # community.docker.docker_secret:
  #   name: "{{ docker_secret.name }}"
  #   data: "{{ docker_secret.data }}"
  template:
    src: "templates/secret.txt.j2"
    dest: "{{ docker_compose_service_folder }}/{{ docker_secret.name }}.txt"
    mode: "{{ docker_secret.mode | default('0600', true) }}"
